name: SkillBridge CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: skillbridge
          POSTGRES_PASSWORD: skillbridge
          POSTGRES_DB: skillbridge
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U skillbridge -d skillbridge"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run migrations
      - name: Run migrations
        run: psql -h localhost -U skillbridge -d skillbridge -f init.sql
        env:
          PGPASSWORD: skillbridge

      # Run seed
      - name: Seed database
        run: psql -h localhost -U skillbridge -d skillbridge -f seed_with_hashes.sql
        env:
          PGPASSWORD: skillbridge

      # Run tests
      - name: Run tests
        run: npm test

      # Lint
      - name: Run linter
        run: npm run lint

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: your-dockerhub-username/skillbridge:latest
